### ISSUE TITLE
AST question, make working with Expression enum easier

### ISSUE THREAD

**Issue by Glyphack** [Boshen/javascript-parser-in-rust#10]
In the tutorial it's suggested to represent Expression as an enum and each expression has it's variant. Inside all variants we are storing a node.

I'm trying to work with use the AST, and it's not easy to access the `node` field without deconstructing to a variant.

I'm curios what happens if we change the representation to this:

```
pub struct Expression {
	node: Node,
	expression_kind: ExpressionKind,
}

pub enum ExpressionKind {
    SomeExpression(SomeExpression),
}
```

Then we can pass this type around in functions and access the node easily.

Does this have negative performance impact or other issues?

**Comment by Boshen** [comment]
My solution to this problem is to use a trait, and manually unpack the enum - https://github.com/web-infra-dev/oxc/blob/main/crates/oxc_ast/src/span.rs

Your pattern works on the theoretical level, and it won't impact any performance. But it would become tedious once you start visiting the AST and need the node (span) information. 

To give an example, https://github.com/web-infra-dev/oxc/blob/786cf8252f2a86dbf33873e619d4b1e5fc21674e/crates/oxc_linter/src/rules/eslint/eq_eq_eq.rs#L62

We need to find the binary expression here, and we immediately lose node (span) information with your AST representation.

**Comment by Glyphack** [comment]
Thank you for the explanation.
